package chucnang;

import client_ui.ket_noi_tcp;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

// giao dien phu dung de tim kiem va tai xuong
public class giao_dien_phu extends javax.swing.JFrame {

    // tham chieu den khung hien thi cua client chinh de ghi log (neu can)
    private javax.swing.JTextArea hienthi_log;

    /**
     * Creates new form giao_dien_phu
     */
    public giao_dien_phu(javax.swing.JTextArea log) {
        this.hienthi_log = log;
        initComponents();
        setSize(500, 400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_tren = new javax.swing.JPanel();
        nhap_timkiem = new javax.swing.JTextField();
        nut_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        danh_sach_tai_lieu = new javax.swing.JList<>();
        pn_duoi = new javax.swing.JPanel();
        nut_taixuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm kiếm và Tải xuống");

        pn_tren.setLayout(new java.awt.FlowLayout());

        nhap_timkiem.setColumns(25);
        pn_tren.add(nhap_timkiem);

        nut_timkiem.setText("Tìm kiếm");
        nut_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_timkiemActionPerformed(evt);
            }
        });
        pn_tren.add(nut_timkiem);

        getContentPane().add(pn_tren, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(danh_sach_tai_lieu);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pn_duoi.setLayout(new java.awt.FlowLayout());

        nut_taixuong.setText("Tải xuống tài liệu đã chọn");
        nut_taixuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_taixuongActionPerformed(evt);
            }
        });
        pn_duoi.add(nut_taixuong);

        getContentPane().add(pn_duoi, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nut_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_timkiemActionPerformed
        String tukhoa = nhap_timkiem.getText();
        String[] ketqua = ket_noi_tcp.tim_kiem_mang(tukhoa);
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String tenfile : ketqua) {
            model.addElement(tenfile);
        }
        
        if (ketqua.length == 0) {
            model.addElement("Không tìm thấy file nào!");
        }
        
        danh_sach_tai_lieu.setModel(model);
    }//GEN-LAST:event_nut_timkiemActionPerformed

    private void nut_taixuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_taixuongActionPerformed
        String tenfile = danh_sach_tai_lieu.getSelectedValue();
        if (tenfile != null && !tenfile.equals("Không tìm thấy file nào!")) {
            ket_noi_tcp.tai_xuong(tenfile, hienthi_log);
            JOptionPane.showMessageDialog(this, "Đã gọi lệnh tải xuống file: " + tenfile);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 file trong danh sách trước khi tải!");
        }
    }//GEN-LAST:event_nut_taixuongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> danh_sach_tai_lieu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nhap_timkiem;
    private javax.swing.JButton nut_taixuong;
    private javax.swing.JButton nut_timkiem;
    private javax.swing.JPanel pn_duoi;
    private javax.swing.JPanel pn_tren;
    // End of variables declaration//GEN-END:variables
}
