package chucnang;

import client_ui.ket_noi_tcp;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

// giao dien phu dung de tim kiem va tai xuong
public class giao_dien_phu extends javax.swing.JFrame {

    // tham chieu den khung hien thi cua client chinh de ghi log (neu can)
    private javax.swing.JTextArea hienthi_log;
    private String[] originalFiles;

    /**
     * Creates new form giao_dien_phu
     */
    public giao_dien_phu(javax.swing.JTextArea log) {
        this.hienthi_log = log;
        initComponents();
        setSize(500, 400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_tren = new javax.swing.JPanel();
        nhap_timkiem = new javax.swing.JTextField();
        nut_timkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        danh_sach_tai_lieu = new javax.swing.JList<>();
        pn_duoi = new javax.swing.JPanel();
        nut_taixuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tìm kiếm và Tải xuống");

        pn_tren.setLayout(new java.awt.FlowLayout());

        nhap_timkiem.setColumns(25);
        pn_tren.add(nhap_timkiem);

        nut_timkiem.setText("Tìm kiếm");
        nut_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_timkiemActionPerformed(evt);
            }
        });
        pn_tren.add(nut_timkiem);

        getContentPane().add(pn_tren, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(danh_sach_tai_lieu);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pn_duoi.setLayout(new java.awt.FlowLayout());

        nut_taixuong.setText("Tải xuống tài liệu đã chọn");
        nut_taixuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nut_taixuongActionPerformed(evt);
            }
        });
        pn_duoi.add(nut_taixuong);

        getContentPane().add(pn_duoi, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nut_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_timkiemActionPerformed
        String tukhoa = nhap_timkiem.getText();
        
        // Ho tro tu dong phan luong Local vs LAN
        String[] ketqua;
        if (chucnang3.PhanLuong.laLocal()) {
            ketqua = chucnang3.KetNoiLocal.tim_kiem_mang(tukhoa);
        } else {
            ketqua = client_ui.ket_noi_tcp.tim_kiem_mang(tukhoa);
        }
        
        this.originalFiles = ketqua; // Luu lai danh sach cac file raw
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String item : ketqua) {
            String[] parts = item.split("\\|");
            String tenfile = parts[0];
            long size = parts.length > 1 ? Long.parseLong(parts[1]) : 0;
            String danhmuc = parts.length > 2 ? parts[2] : "Khác";
            String tags = parts.length > 3 ? parts[3] : "";
            long luotTai = parts.length > 4 ? Long.parseLong(parts[4]) : 0;

            String sizeStr;
            if (size >= 1024 * 1024) {
                sizeStr = String.format("%.1f MB", size / (1024.0 * 1024.0));
            } else if (size >= 1024) {
                sizeStr = String.format("%.1f KB", size / 1024.0);
            } else {
                sizeStr = size + " B";
            }

            // Dinh dang HTML hien thi list item cuc dep
            String formatHtml = "<html><body style='padding: 3px;'>"
                    + "<b>📄 " + tenfile + "</b><br>"
                    + "<font color='#555555'>&nbsp;&nbsp;&nbsp;&nbsp;Danh mục: <b>" + danhmuc + "</b>"
                    + " • Dung lượng: <b>" + sizeStr + "</b>"
                    + " • Lượt tải: <b>" + luotTai + "</b>"
                    + (tags.isEmpty() ? "" : " • Tags: <font color='green'>#" + tags + "</font>")
                    + "</font></body></html>";
            model.addElement(formatHtml);
        }
        
        if (ketqua.length == 0) {
            model.addElement("Không tìm thấy file nào!");
        }
        
        danh_sach_tai_lieu.setModel(model);
    }//GEN-LAST:event_nut_timkiemActionPerformed

    private void nut_taixuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_taixuongActionPerformed
        int index = danh_sach_tai_lieu.getSelectedIndex();
        if (index != -1 && originalFiles != null && index < originalFiles.length) {
            String rawItem = originalFiles[index];
            String tenfile = rawItem.split("\\|")[0];
            
            // Chay ngam de tranh dong bang giao dien va tu dong cap nhat luot tai realtime!
            new Thread(() -> {
                if (chucnang3.PhanLuong.laLocal()) {
                    chucnang3.KetNoiLocal.tai_xuong(tenfile, hienthi_log);
                } else {
                    client_ui.ket_noi_tcp.tai_xuong(tenfile, hienthi_log);
                }
                
                // 1. Tu dong lam moi danh sach o Client chinh de cap nhat luot tai moi nhat
                if (client_ui.client_ui.INSTANCE != null) {
                    client_ui.client_ui.INSTANCE.lamMoiDanhSach();
                }
                
                // 2. Tu dong lam moi danh sach tim kiem hien tai trong giao_dien_phu
                javax.swing.SwingUtilities.invokeLater(() -> {
                    nut_timkiemActionPerformed(null);
                });
            }).start();
            
            JOptionPane.showMessageDialog(this, "Đã gọi lệnh tải xuống file: " + tenfile);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 file trong danh sách trước khi tải!");
        }
    }//GEN-LAST:event_nut_taixuongActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> danh_sach_tai_lieu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nhap_timkiem;
    private javax.swing.JButton nut_taixuong;
    private javax.swing.JButton nut_timkiem;
    private javax.swing.JPanel pn_duoi;
    private javax.swing.JPanel pn_tren;
    // End of variables declaration//GEN-END:variables
}
