/*
 * day la file giao dien chinh cua he thong thu vien tai lieu
 * he thong su dung tcp, udp, rmi
 */
package client_ui;

import java.awt.*;
import java.net.URL;
import javax.swing.*;

// lop chinh cua giao dien
public class client_ui extends javax.swing.JFrame {

    // Global active instance for real-time updates
    public static client_ui INSTANCE;

    // Panel hien thi danh sach tai lieu dang icon
    private JPanel pn_danhsach;

    /**
     * Creates new form client_ui
     */
    public client_ui() {
        INSTANCE = this; // Set global instance
        initComponents();

        // 1. Dat icon cua so (thanh taskbar + goc trai cua so)
        try {
            URL urlIcon = getClass().getClassLoader().getResource("resources/icontl.png");
            if (urlIcon != null) {
                setIconImage(new ImageIcon(urlIcon).getImage());
            }
        } catch (Exception ignored) {}

        // 2. Thay the hienthi_tailieu bang panel hien thi icon
        pn_danhsach = new JPanel();
        pn_danhsach.setLayout(new WrapLayout(FlowLayout.LEFT, 12, 12));
        pn_danhsach.setBackground(Color.WHITE);
        jScrollPane4.setViewportView(pn_danhsach);

        // 3. Thiet lap cua so
        setLocationRelativeTo(null);

        // 4. Bat dau luong nhan udp
        nhan_udp luong_udp = new nhan_udp(hienthi_udp);
        luong_udp.start();

        // 5. Hien thi mac dinh
        hienthi_tcp.setText("ket qua hoat dong tcp hien o day...\n");
        hienthi_udp.setText("dang lang nghe thong bao tai lieu moi (udp)...\n");
        hienthi_rmi.setText("ket qua quan tri rmi hien o day...\n");

        // 5.5. Them hai nut xem danh muc va xem tag qua RMI
        JButton nut_xem_danhmuc = new JButton("xem danh mục");
        nut_xem_danhmuc.addActionListener(e -> {
            goi_rmi.xem_danhmuc(hienthi_rmi);
        });
        pn_rmi_tren.add(nut_xem_danhmuc);

        JButton nut_xem_tag = new JButton("xem tag gợi ý");
        nut_xem_tag.addActionListener(e -> {
            goi_rmi.xem_tag(hienthi_rmi);
        });
        pn_rmi_tren.add(nut_xem_tag);

        // 6. Tai danh sach tai lieu ngay khi mo
        nut_lammoiActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_chinh = new javax.swing.JTabbedPane();
        pn_hienthi = new javax.swing.JPanel();
        pn_hienthi_tren = new javax.swing.JPanel();
        nut_lammoi = new javax.swing.JButton();
        nut_tailen_hienthi = new javax.swing.JButton();
        nut_taixuong_hienthi = new javax.swing.JButton();
        nut_timkiem_hienthi = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        hienthi_tailieu = new javax.swing.JTextArea();
        pn_tcp = new javax.swing.JPanel();
        pn_tcp_tren = new javax.swing.JPanel();
        nhap_timkiem = new javax.swing.JTextField();
        nut_timkiem = new javax.swing.JButton();
        nut_tailen = new javax.swing.JButton();
        nut_taixuong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hienthi_tcp = new javax.swing.JTextArea();
        pn_udp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hienthi_udp = new javax.swing.JTextArea();
        pn_rmi = new javax.swing.JPanel();
        pn_rmi_tren = new javax.swing.JPanel();
        nut_danhmuc = new javax.swing.JButton();
        nut_tag = new javax.swing.JButton();
        nut_thongke = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hienthi_rmi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thư Viện Tài Liệu Môn Học");

        pn_hienthi.setLayout(new java.awt.BorderLayout());

        nut_lammoi.setText("Làm mới");
        nut_lammoi.addActionListener(this::nut_lammoiActionPerformed);
        pn_hienthi_tren.add(nut_lammoi);

        nut_tailen_hienthi.setText("Tải lên");
        nut_tailen_hienthi.addActionListener(this::nut_tailen_hienthiActionPerformed);
        pn_hienthi_tren.add(nut_tailen_hienthi);

        nut_taixuong_hienthi.setText("Tải xuống");
        nut_taixuong_hienthi.addActionListener(this::nut_taixuong_hienthiActionPerformed);
        pn_hienthi_tren.add(nut_taixuong_hienthi);

        nut_timkiem_hienthi.setText("Tìm kiếm");
        nut_timkiem_hienthi.addActionListener(this::nut_timkiem_hienthiActionPerformed);
        pn_hienthi_tren.add(nut_timkiem_hienthi);

        pn_hienthi.add(pn_hienthi_tren, java.awt.BorderLayout.NORTH);

        hienthi_tailieu.setColumns(20);
        hienthi_tailieu.setRows(5);
        hienthi_tailieu.setEditable(false);
        jScrollPane4.setViewportView(hienthi_tailieu);

        pn_hienthi.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        tab_chinh.addTab("Hiển thị", pn_hienthi);

        pn_tcp.setLayout(new java.awt.BorderLayout());

        nhap_timkiem.setColumns(20);
        pn_tcp_tren.add(nhap_timkiem);

        nut_timkiem.setText("tìm kiếm");
        nut_timkiem.addActionListener(this::nut_timkiemActionPerformed);
        pn_tcp_tren.add(nut_timkiem);

        nut_tailen.setText("tải lên");
        nut_tailen.addActionListener(this::nut_tailenActionPerformed);
        pn_tcp_tren.add(nut_tailen);

        nut_taixuong.setText("tai xuong");
        nut_taixuong.addActionListener(this::nut_taixuongActionPerformed);
        pn_tcp_tren.add(nut_taixuong);

        pn_tcp.add(pn_tcp_tren, java.awt.BorderLayout.NORTH);

        hienthi_tcp.setColumns(20);
        hienthi_tcp.setRows(5);
        hienthi_tcp.setEditable(false);
        jScrollPane1.setViewportView(hienthi_tcp);

        pn_tcp.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tab_chinh.addTab("Chức năng TCP", pn_tcp);

        pn_udp.setLayout(new java.awt.BorderLayout());

        hienthi_udp.setColumns(20);
        hienthi_udp.setRows(5);
        hienthi_udp.setEditable(false);
        jScrollPane2.setViewportView(hienthi_udp);

        pn_udp.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tab_chinh.addTab("Chức năng UDP", pn_udp);

        pn_rmi.setLayout(new java.awt.BorderLayout());

        nut_danhmuc.setText("quản lý danh mục");
        nut_danhmuc.addActionListener(this::nut_danhmucActionPerformed);
        pn_rmi_tren.add(nut_danhmuc);

        nut_tag.setText("quản lý tag");
        nut_tag.addActionListener(this::nut_tagActionPerformed);
        pn_rmi_tren.add(nut_tag);

        nut_thongke.setText("thống kê lượt tải");
        nut_thongke.addActionListener(this::nut_thongkeActionPerformed);
        pn_rmi_tren.add(nut_thongke);

        pn_rmi.add(pn_rmi_tren, java.awt.BorderLayout.NORTH);

        hienthi_rmi.setColumns(20);
        hienthi_rmi.setRows(5);
        hienthi_rmi.setEditable(false);
        jScrollPane3.setViewportView(hienthi_rmi);

        pn_rmi.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tab_chinh.addTab("Chức năng RMI", pn_rmi);

        getContentPane().add(tab_chinh, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nut_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_timkiemActionPerformed
        // mo cua so phu
        chucnang.giao_dien_phu giaodien = new chucnang.giao_dien_phu(hienthi_tcp);
        giaodien.setVisible(true);
    }//GEN-LAST:event_nut_timkiemActionPerformed

    private void nut_tailenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_tailenActionPerformed
        javax.swing.JFileChooser chon_file = new javax.swing.JFileChooser();
        chon_file.setDialogTitle("chọn tài liệu để tải lên");
        if (chon_file.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file_da_chon = chon_file.getSelectedFile();
            chucnang2.GiaoDienChonTag.hienThi(this, file_da_chon, hienthi_tcp);
        }
    }//GEN-LAST:event_nut_tailenActionPerformed

    private void nut_taixuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_taixuongActionPerformed
        // cung mo cua so phu giong tim kiem de chon file
        chucnang.giao_dien_phu giaodien = new chucnang.giao_dien_phu(hienthi_tcp);
        giaodien.setVisible(true);
    }//GEN-LAST:event_nut_taixuongActionPerformed

    private void nut_danhmucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_danhmucActionPerformed
        String tendanhmuc = JOptionPane.showInputDialog(this, "nhap ten danh muc moi:");
        if (tendanhmuc != null && !tendanhmuc.isEmpty()) {
            goi_rmi.them_danhmuc(tendanhmuc, hienthi_rmi);
        }
    }//GEN-LAST:event_nut_danhmucActionPerformed

    private void nut_tagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_tagActionPerformed
        String tentag = JOptionPane.showInputDialog(this, "nhap ten tag moi:");
        if (tentag != null && !tentag.isEmpty()) {
            goi_rmi.them_tag(tentag, hienthi_rmi);
        }
    }//GEN-LAST:event_nut_tagActionPerformed

    private void nut_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nut_thongkeActionPerformed
        goi_rmi.xem_thongke(hienthi_rmi);
    }//GEN-LAST:event_nut_thongkeActionPerformed

    public void lamMoiDanhSach() {
        new Thread(() -> {
            String[] danhsach;
            if (chucnang3.PhanLuong.laLocal()) {
                danhsach = chucnang3.KetNoiLocal.tim_kiem_mang("");
            } else {
                danhsach = ket_noi_tcp.tim_kiem_mang("");
            }
            SwingUtilities.invokeLater(() -> hienThiDanhSachIcon(danhsach));
        }).start();
    }

    private void nut_lammoiActionPerformed(java.awt.event.ActionEvent evt) {
        lamMoiDanhSach();
    }

    // Hien thi danh sach tai lieu dang icon card voi hinh anh dai dien
    private void hienThiDanhSachIcon(String[] danhsach) {
        pn_danhsach.removeAll();

        // Load icon tai lieu (icontl.png)
        ImageIcon iconGoc = null;
        try {
            URL url = getClass().getClassLoader().getResource("resources/icontl.png");
            if (url != null) {
                Image img = new ImageIcon(url).getImage().getScaledInstance(64, 64, Image.SCALE_SMOOTH);
                iconGoc = new ImageIcon(img);
            }
        } catch (Exception ignored) {}
        final ImageIcon icon = iconGoc;

        if (danhsach.length == 0) {
            JLabel lbl = new JLabel("Chưa có tài liệu nào.", SwingConstants.CENTER);
            lbl.setFont(new Font("Segoe UI", Font.ITALIC, 14));
            lbl.setForeground(Color.GRAY);
            pn_danhsach.add(lbl);
        } else {
            for (String item : danhsach) {
                // Item dang: tenfile|size|category|tags|downloads
                String[] parts = item.split("\\|");
                String tenfile = parts[0];
                long size = parts.length > 1 ? Long.parseLong(parts[1]) : 0;
                String danhmuc = parts.length > 2 ? parts[2] : "Khác";
                String tags = parts.length > 3 ? parts[3] : "";
                long luotTai = parts.length > 4 ? Long.parseLong(parts[4]) : 0;

                // Dinh dang dung luong
                String sizeStr;
                if (size >= 1024 * 1024) {
                    sizeStr = String.format("%.1f MB", size / (1024.0 * 1024.0));
                } else if (size >= 1024) {
                    sizeStr = String.format("%.1f KB", size / 1024.0);
                } else {
                    sizeStr = size + " B";
                }

                // Moi file la 1 card: icon + ten file + metadata
                JPanel card = new JPanel();
                card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
                card.setBackground(new Color(248, 249, 252));
                card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(new Color(220, 220, 230), 1, true),
                    javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
                ));
                card.setPreferredSize(new Dimension(150, 150));
                card.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                // Icon
                JLabel lblIcon = new JLabel(icon != null ? icon : new ImageIcon());
                lblIcon.setAlignmentX(Component.CENTER_ALIGNMENT);

                // Ten file (rut gon neu qua dai)
                String hienThi = tenfile.length() > 18 ? tenfile.substring(0, 15) + "..." : tenfile;
                JLabel lblTen = new JLabel(hienThi, SwingConstants.CENTER);
                lblTen.setFont(new Font("Segoe UI", Font.BOLD, 11));
                lblTen.setForeground(new Color(40, 40, 60));
                lblTen.setAlignmentX(Component.CENTER_ALIGNMENT);

                // Subtext 1: Danh muc
                JLabel lblDM = new JLabel(danhmuc, SwingConstants.CENTER);
                lblDM.setFont(new Font("Segoe UI", Font.ITALIC, 9));
                lblDM.setForeground(new Color(100, 110, 140));
                lblDM.setAlignmentX(Component.CENTER_ALIGNMENT);

                // Subtext 2: Kich thuoc & Luot tai
                JLabel lblInfo = new JLabel(sizeStr + " • " + luotTai + " lượt tải", SwingConstants.CENTER);
                lblInfo.setFont(new Font("Segoe UI", Font.PLAIN, 9));
                lblInfo.setForeground(new Color(120, 120, 130));
                lblInfo.setAlignmentX(Component.CENTER_ALIGNMENT);

                // Subtext 3: Tags (rut gon)
                String tagsHienThi = tags.isEmpty() ? "Không tag" : (tags.length() > 18 ? tags.substring(0, 15) + "..." : tags);
                JLabel lblTags = new JLabel("[" + tagsHienThi + "]", SwingConstants.CENTER);
                lblTags.setFont(new Font("Segoe UI", Font.PLAIN, 9));
                lblTags.setForeground(new Color(34, 139, 34)); // Mau xanh la
                lblTags.setAlignmentX(Component.CENTER_ALIGNMENT);

                // Hover Tooltip (dung HTML de format)
                String toolTip = "<html><body style='width: 200px; padding: 4px;'>"
                        + "<b>Tài liệu:</b> " + tenfile + "<br>"
                        + "<b>Danh mục:</b> " + danhmuc + "<br>"
                        + "<b>Dung lượng:</b> " + sizeStr + "<br>"
                        + "<b>Lượt tải:</b> " + luotTai + " lượt<br>"
                        + "<b>Tags:</b> " + (tags.isEmpty() ? "Không có" : tags)
                        + "</body></html>";
                card.setToolTipText(toolTip);

                // Hover effect sang mau nhe + click tai nhanh
                card.addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                        card.setBackground(new Color(235, 238, 255));
                    }
                    @Override public void mouseExited(java.awt.event.MouseEvent e) {
                        card.setBackground(new Color(248, 249, 252));
                    }
                    @Override public void mouseClicked(java.awt.event.MouseEvent e) {
                        if (e.getClickCount() == 2) { // Double click de tai nhanh
                            int xacNhan = JOptionPane.showConfirmDialog(null, 
                                    "Bạn có muốn tải xuống tài liệu \"" + tenfile + "\" không?", 
                                    "Tải Xuống Nhanh", 
                                    JOptionPane.YES_NO_OPTION,
                                    JOptionPane.QUESTION_MESSAGE);
                            if (xacNhan == JOptionPane.YES_OPTION) {
                                new Thread(() -> {
                                    if (chucnang3.PhanLuong.laLocal()) {
                                        chucnang3.KetNoiLocal.tai_xuong(tenfile, hienthi_tailieu);
                                    } else {
                                        ket_noi_tcp.tai_xuong(tenfile, hienthi_tailieu);
                                    }
                                    // Tu dong lam moi de cap nhat luot tai moi nhat
                                    lamMoiDanhSach();
                                }).start();
                            }
                        }
                    }
                });

                card.add(lblIcon);
                card.add(Box.createVerticalStrut(4));
                card.add(lblTen);
                card.add(Box.createVerticalStrut(2));
                card.add(lblDM);
                card.add(Box.createVerticalStrut(2));
                card.add(lblInfo);
                card.add(Box.createVerticalStrut(2));
                card.add(lblTags);

                pn_danhsach.add(card);
            }
        }

        pn_danhsach.revalidate();
        pn_danhsach.repaint();
    }

    private void nut_tailen_hienthiActionPerformed(java.awt.event.ActionEvent evt) {
        javax.swing.JFileChooser chon_file = new javax.swing.JFileChooser();
        chon_file.setDialogTitle("chọn tài liệu để tải lên");
        if (chon_file.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file_da_chon = chon_file.getSelectedFile();
            chucnang2.GiaoDienChonTag.hienThi(this, file_da_chon, hienthi_tailieu);
        }
    }

    private void nut_taixuong_hienthiActionPerformed(java.awt.event.ActionEvent evt) {
        chucnang.giao_dien_phu giaodien = new chucnang.giao_dien_phu(hienthi_tailieu);
        giaodien.setVisible(true);
    }

    private void nut_timkiem_hienthiActionPerformed(java.awt.event.ActionEvent evt) {
        chucnang.giao_dien_phu giaodien = new chucnang.giao_dien_phu(hienthi_tailieu);
        giaodien.setVisible(true);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(client_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(client_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(client_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(client_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        // Phan luong tu dong: kiem tra local truoc, chi hoi IP LAN khi khong co server local
        chucnang3.PhanLuong.CheDo cheDo = chucnang3.PhanLuong.xacDinhKetNoi();

        // Hien thi thong bao ket noi (thanh cong / that bai)
        thongbao.HopThoaiThongBao.hienThiVaKiemTra(CauHinh.SERVER_IP);

        System.out.println("[CLIENT] Che do ket noi: " + cheDo 
            + " | Server IP: " + CauHinh.SERVER_IP);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new client_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea hienthi_rmi;
    private javax.swing.JTextArea hienthi_tailieu;
    private javax.swing.JTextArea hienthi_tcp;
    private javax.swing.JTextArea hienthi_udp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nhap_timkiem;
    private javax.swing.JButton nut_danhmuc;
    private javax.swing.JButton nut_lammoi;
    private javax.swing.JButton nut_tag;
    private javax.swing.JButton nut_tailen;
    private javax.swing.JButton nut_tailen_hienthi;
    private javax.swing.JButton nut_taixuong;
    private javax.swing.JButton nut_taixuong_hienthi;
    private javax.swing.JButton nut_thongke;
    private javax.swing.JButton nut_timkiem;
    private javax.swing.JButton nut_timkiem_hienthi;
    private javax.swing.JPanel pn_hienthi;
    private javax.swing.JPanel pn_hienthi_tren;
    private javax.swing.JPanel pn_rmi;
    private javax.swing.JPanel pn_rmi_tren;
    private javax.swing.JPanel pn_tcp;
    private javax.swing.JPanel pn_tcp_tren;
    private javax.swing.JPanel pn_udp;
    private javax.swing.JTabbedPane tab_chinh;
    // End of variables declaration//GEN-END:variables
}
